import React from "react";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Card from "@/components/Card";
import { EmployeeDataContext } from "./_app";

export default function Home() {
  const { employeeData } = React.useContext(EmployeeDataContext);
  const [employeeDataSet, setEmployeeDataSet] = React.useState(employeeData);
  const [search, setSearch] = React.useState("");

  React.useEffect(() => {
    setEmployeeDataSet(employeeData);
  }, [employeeData]);

  React.useEffect(() => {
    if (search) {
      const filteredData = employeeData.filter((employee) => {
        return employee.name.toLowerCase().includes(search.toLowerCase());
      });
      setEmployeeDataSet(filteredData);
    } else {
      setEmployeeDataSet(employeeData);
    }
  }, [search]);

  return (
    <>
      <Head>
        <title>Employee Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex flex-col items-center justify-center">
        <Navbar search={search} setSearch={setSearch} />
        <div className="grid grid-cols-3 mt-32 gap-10 w-10/12 items-center justify-center pb-10">
          {console.log(employeeDataSet)}
          {employeeDataSet ? (
            employeeDataSet.map((employee, key) => (
              <Card key={key} data={employee} />
            ))
          ) : (
            <div className="text-2xl">Loading...</div>
          )}
        </div>
      </main>
    </>
  );
}
